export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'

export const OBTENER_TURNOS = 'OBTENER_TURNOS'
export const AGREGAR_TURNO = 'AGREGAR_TURNO'
export const ELIMINAR_TURNO = 'ELIMINAR_TURNO'
export const OBTENER_TURNOS_X_FECHA = 'OBTENER_TURNOS_X_FECHA'
